#!/bin/sh
#------------------------------
# Create device file for MPIO
#------------------------------

DEVFILE=/dev/usb/mpio
MAJOR=180
MINOR=70
PERM=666
OWNER=root.root

if test -c $DEVFILE; then
    echo -n "Removing $DEVFILE ... "
    rm -f $DEVFILE
    echo "done"
fi

if test "$1" != "-r"; then
    echo -n "Creating $DEVFILE ... "
    mknod -m $PERM $DEVFILE c $MAJOR $MINOR
    chown $OWNER $DEVFILE
    echo "done"
fi

